In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

In [4]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [5]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

In [6]:
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [7]:
C = np.random.rand(3, 5)

In [8]:
C

array([[0.08631565, 0.56674178, 0.16941501, 0.73336891, 0.84111291],
       [0.39251186, 0.53001646, 0.74179258, 0.27874542, 0.54773838],
       [0.52480598, 0.91609397, 0.82762884, 0.19671227, 0.41761424]])

In [10]:
D = np.zeros([2, 4])

In [11]:
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
A[0][2]

2